name: pytorch-gpu-tutorial

channels:
  - pytorch
  - fastai
  - defaults

dependencies: 
  - pandas=0.24.*
  - python=3.7.*
  - matplotlib=3.0.*
  - jupyterlab
  - scikit-learn=0.20.*
  - pytorch
  - torchvision
  - fastai
  - pip:
    - kaggle==1.5.*
