name: null

channels:
  - pytorch
  - fastai
  - defaults
  - conda-forge

dependencies: 
  - pandas=0.24
  - python=3.7
  - matplotlib=3.0
  - jupyterlab=1.0
  - scikit-learn=0.21
  - pytorch=1.1
  - torchvision=0.3
  - fastai=1.0
  - kaggle=1.5
