name: null

channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults

dependencies: 
  - fastai=1.0
  - jupyterlab=1.2
  - kaggle=1.5
  - matplotlib=3.1
  - pandas=0.25
  - pip=19.3
  - python=3.7
  - pytorch=1.3
  - scikit-learn=0.22
  - torchvision=0.4
  - pip:
    - pretrainedmodels==0.7
